version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    ports:
      - "5433:5432"

  api:
    build:
      context: ./

    working_dir: /home/node/app
    ports:
      - ${PORT}:${PORT}

    command: /bin/sh -c "npm run dev"
    volumes:
      - './:/home/node/app'